#!/usr/bin/env python3
"""Single-machine bench for the WAMCES device records.

The full case is 3809 buses and RAMSES free builds refuse anything above 1000,
so the converted `SYNC_MACH` / `EXC ST1A_PSS2B` / `TOR TGOV1` records cannot be
exercised at full size without a licence. This builds a two-bus case carrying
*the same records*, produced by the same functions in wamces_to_ramses.py, so
that record syntax, parameter order and model initialisation are all checked
on something that runs under the free limit.

The check is the house one: with no disturbance the machine must initialise and
then sit exactly still. Drift at t = 0 means the parameters are inconsistent.

    python3 tools/bench_machine.py
"""

import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from wamces_to_ramses import exc_st1a_pss2b, tor_tgov1, read_csv  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
BENCH = ROOT / "tools" / "bench"

VNOM = 380.0        # kV
SNOM = 1500.0       # MVA, machine rating
PLOAD = 1000.0      # MW
QLOAD = 100.0       # Mvar


def build(csv_dir):
    machines = read_csv(csv_dir / "data_sm.csv")
    avrs = read_csv(csv_dir / "data_avr.csv")
    psss = read_csv(csv_dir / "data_pss.csv")
    turs = read_csv(csv_dir / "data_tur.csv")
    mac, avr, pss, tur = machines[0], avrs[0], psss[0], turs[0]

    BENCH.mkdir(parents=True, exist_ok=True)

    # Line impedance: 0.001 + j0.02 pu on 100 MVA, converted to ohms.
    zbase = VNOM * VNOM / 100.0
    r_ohm, x_ohm = 0.001 * zbase, 0.02 * zbase

    (BENCH / "bench_lf.dat").write_text(
        "! Single-machine bench for the WAMCES device records. Generated by tools/bench_machine.py.\n"
        "\n"
        f"BUS B1 {VNOM} 0. 0. 0. 0. ;\n"
        f"BUS B2 {VNOM} {PLOAD} {QLOAD} 0. 0. ;\n"
        "\n"
        f"LINE L12 B1 B2 {r_ohm:.6f} {x_ohm:.6f} 0. 0. 1 ;\n"
        "\n"
        f"GENER G1 B1 {PLOAD} {QLOAD} 1.0 {SNOM} -9999. 9999. 1 ;\n"
        "\n"
        "SLACK B1 ;\n"
    )

    exc = " ".join(f"{v:g}" for _, v in exc_st1a_pss2b(avr, pss))
    tor = " ".join(f"{v:g}" for _, v in tor_tgov1(tur))
    (BENCH / "bench_dyn.dat").write_text(
        "! Same device records as wamces_dyn.dat, on one machine.\n"
        "\n"
        "FNOM 50.0 ;\n"
        "\n"
        f"SYNC_MACH G1 B1 1. 1. 0. 0. {SNOM} {SNOM} "
        f"{float(mac['H']):g} {float(mac['D']):g} 1.\n"
        f"   XT {float(mac['Xl']):g} {float(mac['Xd']):g} {float(mac['Xd1']):g} "
        f"{float(mac['Xd2']):g} {float(mac['Xq']):g} {float(mac['Xq1']):g} "
        f"{float(mac['Xq2']):g} 0. 0. {float(mac['Ra']):g} "
        f"{float(mac['Td01']):g} {float(mac['Td02']):g} "
        f"{float(mac['Tq01']):g} {float(mac['Tq02']):g}\n"
        f"   EXC ST1A_PSS2B {exc}\n"
        f"   TOR TGOV1 {tor} ;\n"
    )

    (BENCH / "bench_settings.dat").write_text(
        "$NEWTON_TOLER 0.0001 0.0001 0.0001 ;\n"
        "$FIN_DIFFER 0.00001 0.00001        ;\n"
        "$PLOT_STEP  0.01                   ;\n"
        "$DISP_PROF T                       ;\n"
        "$NB_THREADS 1                      ;\n"
        "$T_LOAD_REST 0.005                 ;\n"
        "$FULL_UPDATE F                     ;\n"
        "$SKIP_CONV T                       ;\n"
        "$LATENCY 20. F                     ;\n"
        "$SCHEME DE                         ;\n"
        "$OMEGA_REF COI                     ;\n"
        "$SPARSE_SOLVER KLU                 ;\n"
    )
    (BENCH / "bench_flat.dst").write_text(
        "0.000 CONTINUE SOLVER BD 0.0200 0.001 0. ALL\n"
        "20.000 STOP\n"
    )
    (BENCH / "bench_obs.dat").write_text("SYNC *\n")


def solve_and_run():
    from stepss.helios import HeliosSession
    import stepss

    pf = HeliosSession()
    pf.load_file(str(BENCH / "bench_lf.dat"))
    if not pf.solve():
        sys.exit("bench power flow did not converge")
    pf.write_voltrat(str(BENCH / "bench_lfres.dat"))
    print(f"power flow: converged in {pf.iterations} iterations, "
          f"{pf.bus_count} buses, {pf.generator_count} generators")
    pf.close()

    case = stepss.cfg()
    for f in ("bench_lf.dat", "bench_lfres.dat", "bench_dyn.dat", "bench_settings.dat"):
        case.addData(str(BENCH / f))
    case.addDst(str(BENCH / "bench_flat.dst"))
    case.addObs(str(BENCH / "bench_obs.dat"))
    case.addTrj(str(BENCH / "bench_flat.trj"))
    stepss.sim().execSim(case)
    print("dynamic run: completed")

    ext = stepss.extractor(str(BENCH / "bench_flat.trj"))
    return ext


def main():
    csv_dir = ROOT / "original-data" / "csv"
    if not csv_dir.is_dir():
        sys.exit(f"{csv_dir} missing: unzip original-data/raw_csv_data.zip into it first")
    build(csv_dir)
    print(f"bench written to {BENCH}")
    ext = solve_and_run()
    print(ext)


if __name__ == "__main__":
    main()
