#!/usr/bin/env python3
"""Convert the published WAMCES MATLAB model into RAMSES/HELIOS data files.

Reads the CSV export of the nine `data_*` tables plus `powerflow_sol.mat`, and
writes the static network and its operating point:

    wamces_lf.dat      BUS / LINE / TRANSFO / GENER / SLACK   (HELIOS input)
    wamces_lfres.dat   LFRESV records                          (the published operating point)

Run from the repository root:

    python3 tools/wamces_to_ramses.py

Conversions that are not one-to-one, and why:

* **Impedances change units.** WAMCES gives R and X in per unit on 100 MVA.
  A RAMSES `LINE` wants ohms, so R_ohm = R_pu * Vnom^2 / 100. A `TRANSFO`
  wants percent on its own SNOM, and SNOM is fixed at 100 MVA here so that
  percent equals per unit times 100 exactly.
* **Branches are split by voltage level.** WAMCES has one branch table and no
  transformer flag. RAMSES forbids a LINE between two nominal voltages, so a
  branch whose ends differ becomes a TRANSFO at nominal ratio (N=100, PHI=0),
  which is exactly how the MATLAB admittance builder treats it.
* **The operating point comes from `powerflow_sol.mat`.** The Vmag/Vang/Pgen/
  Qgen/Ploa/Qloa columns of `data_bus` describe a different snapshot and are
  deliberately ignored, as the MATLAB script also ignores them.
* **One slack, not five.** The published solution holds five buses at 1.0 angle
  0. RAMSES takes a single SLACK, so the largest is chosen and the other four
  become ordinary voltage-imposed generators at their solved voltage.

Line charging, taps, phase shifts and bus shunts are all identically zero in
the published data and are emitted as zero.
"""

import argparse
import csv
import pathlib
import sys

try:
    import scipy.io as sio
except ImportError:
    sys.exit("scipy is required: pip install scipy")

SBASE = 100.0          # MVA, the WAMCES system base
TRAFO_SNOM = 100.0     # MVA, chosen so that percent-on-SNOM equals per-unit * 100
WIDE = 9999.0          # stand-in for a limit the source data does not model
NO_LIMIT = 10.0        # converter current limit, in pu on the converter base.
                       # WAMCES models no current limit, and leaving the model
                       # default of 1.0 makes the converters chatter on it during
                       # a disturbance: the solver drops to its minimum time step
                       # and a 51 s run does not finish. Ten times rating never
                       # binds without pushing the saturation logic to extremes.


def read_csv(path):
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh))


def bus_name(rec):
    """Country code plus the original global bus id: 'FR889'. At most 6 chars."""
    return f"{rec['Country']}{rec['ID']}"


def load_inputs(csv_dir, mat_path):
    buses = read_csv(csv_dir / "data_bus.csv")
    lines = read_csv(csv_dir / "data_lin.csv")
    machines = read_csv(csv_dir / "data_sm.csv")

    sol = sio.loadmat(mat_path)["bus_results"]
    if sol.shape[0] != len(buses):
        sys.exit(f"bus count mismatch: {sol.shape[0]} in the solution, {len(buses)} in data_bus")

    # bus_results columns: id, type, Vmag, Vang, Pgen, Qgen, Ploa, Qloa (pu on SBASE)
    return buses, lines, machines, sol


def write_lf(path, buses, lines, machines, sol):
    by_id = {int(r["ID"]): r for r in buses}
    counts = {"line": 0, "transfo": 0, "gener": 0}

    # --- pick the slack: the type-1 bus carrying the most active power -------
    slack_candidates = [int(r["ID"]) for r in buses if r["Type"] == "1"]
    if not slack_candidates:
        sys.exit("no type-1 bus found to use as slack")
    slack_id = max(slack_candidates, key=lambda i: sol[i - 1, 4])

    out = [
        "! WAMCES: dynamic model of the European power system, static network and operating point.",
        "! Generated by tools/wamces_to_ramses.py from the published CSV tables and powerflow_sol.mat.",
        "! Impedances converted from per unit on 100 MVA: LINE in ohms, TRANSFO in percent on 100 MVA.",
        "! Do not add per-record comments: RAMSES holds them in a fixed buffer that a file this size overflows.",
        "",
    ]

    # --- buses, carrying their load -----------------------------------------
    for rec in buses:
        i = int(rec["ID"])
        pload = sol[i - 1, 6] * SBASE
        qload = sol[i - 1, 7] * SBASE
        out.append(f"BUS {bus_name(rec)} {rec['Vr']} {pload:.4f} {qload:.4f} 0. 0. ;")
    out.append("")

    # --- branches, split into lines and transformers -------------------------
    seen = {}
    for rec in lines:
        i, j = int(rec["ID1"]), int(rec["ID2"])
        bi, bj = by_id[i], by_id[j]
        vi, vj = float(bi["Vr"]), float(bj["Vr"])
        key = (min(i, j), max(i, j))
        seen[key] = seen.get(key, 0) + 1
        circuit = seen[key]
        r_pu, x_pu = float(rec["R"]), float(rec["X"])

        if vi == vj:
            zbase = vi * vi / SBASE          # ohms
            name = f"L{i}_{j}_{circuit}"
            out.append(
                f"LINE {name} {bus_name(bi)} {bus_name(bj)} "
                f"{r_pu * zbase:.6f} {x_pu * zbase:.6f} 0. 0. 1 ;"
            )
            counts["line"] += 1
        else:
            scale = 100.0 * TRAFO_SNOM / SBASE   # per unit on SBASE -> percent on TRAFO_SNOM
            name = f"T{i}_{j}_{circuit}"
            out.append(
                f"TRANSFO {name} {bus_name(bi)} {bus_name(bj)} "
                f"{r_pu * scale:.6f} {x_pu * scale:.6f} 0. 0. 100. 0. {TRAFO_SNOM} 1 ;"
            )
            counts["transfo"] += 1
    out.append("")

    # --- generators ----------------------------------------------------------
    for rec in machines:
        i = int(rec["BusID"])
        p = sol[i - 1, 4] * SBASE
        q = sol[i - 1, 5] * SBASE
        vimp = sol[i - 1, 2]
        snom = float(rec["Sr"])
        if i == slack_id:
            continue                      # emitted as the slack generator below
        out.append(
            f"GENER G{i} {bus_name(by_id[i])} {p:.4f} {q:.4f} {vimp:.6f} "
            f"{snom:.1f} {-WIDE} {WIDE} 1 ;"
        )
        counts["gener"] += 1

    slack_rec = next(r for r in machines if int(r["BusID"]) == slack_id)
    out.append(
        f"GENER G{slack_id} {bus_name(by_id[slack_id])} "
        f"{sol[slack_id - 1, 4] * SBASE:.4f} {sol[slack_id - 1, 5] * SBASE:.4f} "
        f"{sol[slack_id - 1, 2]:.6f} {float(slack_rec['Sr']):.1f} {-WIDE} {WIDE} 1 ;"
    )
    counts["gener"] += 1
    out.append("")
    # SLACK names the bus, not the generator. A PV generator must sit on it;
    # its GENER voltage is imposed and the angle is pinned to zero.
    out.append(f"SLACK {bus_name(by_id[slack_id])} ;")
    out.append("")

    path.write_text("\n".join(out))
    return counts, slack_id


def write_lfres(path, buses, sol):
    out = [
        "! WAMCES operating point, taken verbatim from powerflow_sol.mat (bus_results columns 3 and 4).",
        "! LFRESV PHASV is in RADIANS, not degrees, and is referenced to the slack bus.",
        "",
    ]
    for rec in buses:
        i = int(rec["ID"])
        vm = sol[i - 1, 2]
        va_rad = sol[i - 1, 3]
        out.append(f"LFRESV {bus_name(rec)} {vm:.9f} {va_rad:.9f} ;")
    out.append("")
    path.write_text("\n".join(out))
    return len(buses)


# --- controller parameters -------------------------------------------------
# All 618 AVRs, PSSs and turbines in the published data are identical, so each
# of these is one template repeated 618 times. Values marked "WAMCES" are taken
# from data_avr / data_pss / data_tur; the rest are the settings that make the
# stock model reduce to the WAMCES structure.

def exc_st1a_pss2b(avr, pss):
    """ST1A + PSS2B parameters reproducing the WAMCES AVR and PSS exactly.

    The AVR maps one-to-one: ST1A's amplifier block is KA/(1+sTA), and that lag
    plays the role of the WAMCES exciter constant TE. The second lead-lag is
    bypassed with TC1 = TB1 = 0 and rate feedback disabled with KF = 0.

    The PSS is the degenerate PSS2B that WAMCES implements: no ramp-tracking
    filter (T8 = T9 = 0) and KS3 = 1, which makes the power path cancel
    identically and leaves a speed-only stabilizer. Verified against the
    Simulink wiring: Add is (speed + KS3*power), Add1 subtracts power.
    WAMCES has two washouts on speed and one on power, so T6 = TW4 = 0.
    """
    return [
        ("Kv", 1.0), ("Rc", 0.0), ("Xc", 0.0),
        ("TR", float(avr["Tr"])),                  # WAMCES
        ("UEL", 1.0), ("VIMIN", -WIDE), ("VIMAX", WIDE), ("VUEL", 0.0),
        ("TC", float(avr["TA"])),                  # WAMCES lead
        ("TB", float(avr["TB"])),                  # WAMCES lag
        ("TC1", 0.0), ("TB1", 0.0),                # second lead-lag bypassed
        ("KA", float(avr["KA"])),                  # WAMCES
        ("TA", float(avr["TE"])),                  # WAMCES exciter lag
        ("VAMIN", -WIDE), ("VAMAX", WIDE), ("VRMIN", -WIDE), ("VRMAX", WIDE),
        ("KC", 0.0), ("KF", 0.0), ("TF", 1.0),     # rate feedback off (TF nonzero, KF zero)
        ("KLR", 0.0), ("ILR", 0.0),
        ("speedinput", 1.0),                       # VSI1 = speed, VSI2 = power
        ("TW1", float(pss["TW1"])), ("TW2", float(pss["TW2"])),
        ("T6", 0.0),                               # no speed transducer in WAMCES
        ("TW3", float(pss["TW3"])),
        ("TW4", 0.0),                              # single washout on power
        ("T7", float(pss["T7"])),
        ("KS2", float(pss["KS2"])), ("KS3", float(pss["KS3"])),
        ("T8", 0.0), ("T9", 0.0),                  # ramp-tracking filter bypassed
        ("KS1", float(pss["KS1"])),
        ("T1", float(pss["T1"])), ("T2", float(pss["T2"])),
        ("T3", float(pss["T3"])), ("T4", float(pss["T4"])),
        ("T10", 0.0), ("T11", 0.0),                # third lead-lag unused
        ("VS1MIN", -WIDE), ("VS1MAX", WIDE),
        ("VS2MIN", -WIDE), ("VS2MAX", WIDE),
        ("VSTMIN", -WIDE), ("VSTMAX", WIDE),
    ]


def tor_tgov1(tur):
    """TGOV1 parameters. WAMCES models no valve limits and no turbine damping,
    so VMAX/VMIN are opened out and Dt is zero. Parameter order follows the
    prm() contract of tor_TGOV1D.f90, not the published usage example."""
    return [
        ("R", float(tur["R"])), ("T1", float(tur["T1"])),
        ("VMAX", WIDE), ("VMIN", -WIDE),
        ("T2", float(tur["T2"])), ("T3", float(tur["T3"])),
        ("Dt", 0.0),
    ]


def shunt_impedance(yf_text):
    """Filter impedance in pu from the table's complex admittance, e.g. '0-1.25i'.

    Every converter in the published data carries Yf = -1.25j, so Z = 1/Yf is
    purely inductive at 0.8 pu and the model's R is zero.
    """
    yf = complex(yf_text.replace("i", "j").replace(" ", ""))
    z = 1.0 / yf
    return z.real + 0.0, z.imag + 0.0    # normalise negative zero


def inj_gfor(gfm):
    """GFOR parameters for a WAMCES grid-forming converter.

    The WAMCES synchronization loop is a swing-based virtual synchronous
    machine. Tracing the Simulink blocks gives

        dw/dt     = Ki * (P0 - Pe - Kf*w)
        ddelta/dt = wn * (w - w_sys)

    so Ki is 1/(2H) and Kf is the damping, making H = 4 s, the same inertia the
    synchronous machines carry.

    NOTE the paper writes this as `Ki dw/dt = Pref - P - Kf w` (eq. 33), which
    puts Ki on the other side and would make H = Ki/2 = 0.0625 s, a factor of
    64 smaller. The implementation is what the model simulates: the block named
    Ki is a gain feeding the integrator, not a divisor. 4 s is also the only
    physically sensible reading for a device whose stated job is emulating
    inertia. Follow the source, as with the WT3 parameter contract.

    Kw, which the script zeroes, is neither of these: it is the wide-area
    damping control gain (eq. 65), applied to the difference between the
    delayed global frequency average and the local frequency. Zeroing it turns
    the wide-area control off, which is the open-loop base case. The grid-
    forming converters are the actuators of that control, so this is where an
    externally driven WAMC would inject its signal.

    Imax, Te and r have no counterpart in the source data and take the model's
    documented defaults. Imax = 1 pu never binds here because every converter
    is dispatched at zero, but it is a real difference from WAMCES, which
    models no current limit at all.
    """
    r, x = shunt_impedance(gfm["Yf"])
    ki = float(gfm["Ki"])
    return [
        ("R", r), ("L", x), ("r", 1.0),
        ("Snom", float(gfm["Sr"])),
        ("H", 1.0 / (2.0 * ki)),          # Ki = 1/(2H)
        ("D", float(gfm["Kf"])),          # damping
        ("Tpll", 0.1),                    # default: WAMCES is power-synchronised, no PLL
        ("Rdroop", 999.0),                # no frequency droop term in the source loop
        ("Imax", 1.0),                    # default; WAMCES models no limit
        ("Te", 0.001),                    # default
    ]


def inj_gfol(gfl):
    """GFOL parameters for a WAMCES grid-following converter.

    The two power loops map one-to-one: WAMCES drives Id from a PI on active
    power and Iq from a PI on reactive power, which are GFOL's Kpp/Kip and
    Kpv/Kiv with vqswitch = 0 selecting reactive power rather than voltage.

    The PLL is the one genuine reduction. WAMCES uses a PI PLL, hard-coded in
    the model as 60/wn and 900/wn and matching the table's Kpllp and Kplli, so
    it is second order with wn = sqrt(900) = 30 rad/s and unity damping. GFOL
    exposes a single first-order `tau`, taken here as 1/wn. The critically
    damped pair collapses to one pole; the settling time is comparable but the
    shape is not identical.

    WAMCES has no inner current loop at all: its power PIs output the current
    references directly. GFOL's current control, its limits and its fault-ride
    -through thresholds therefore take documented defaults.
    """
    r, x = shunt_impedance(gfl["Yf"])
    pll_wn = float(gfl["Kplli"]) ** 0.5
    return [
        ("R", r), ("L", x), ("r", 1.0),
        ("Snom", float(gfl["Sr"])),
        ("Rc", 0.0), ("Xc", 0.0),         # no compensated-voltage control
        ("Kp", 0.573), ("Ki", 6.0),       # default inner current loop
        ("Tlpf", float(gfl["Tr"])),
        ("Kpp", float(gfl["Kpp"])), ("Kip", float(gfl["Kpi"])),
        ("Trlim", 0.002),
        ("dPdt_min", -999.0), ("dPdt_max", 10.0),
        ("Kpv", float(gfl["Kqp"])), ("Kiv", float(gfl["Kqi"])),
        ("tau", 1.0 / pll_wn),            # PI PLL reduced to one pole
        ("Vpllb", 0.4), ("Vpllu", 0.5),
        ("Imax", NO_LIMIT),
        ("Vs1", -1000.0), ("Vs2", -2000.0),
        ("iqmax", NO_LIMIT),
        ("vqswitch", 0.0),                # reactive power control, as WAMCES
    ]


PMU_TF_FLOOR = 0.05   # inj_PMU clamps Tf below this


def inj_pmu(pmu):
    """PMU frequency measurement time constant.

    The WAMCES PMU is a PI PLL and nothing else (paper eq. 57-60), so its
    measurement dynamics come from Kp and Ki: wn = sqrt(Ki) = 30 rad/s with
    unity damping, an equivalent time constant of 1/wn = 0.033 s.

    Td is NOT a measurement constant. It is the communication latency of the
    wide-area link, modelled upstream as a second-order Pade approximant
    (eq. 61-63) and used to delay this PMU's reading on its way to the central
    unit (eq. 64). It belongs to the control layer, which is driven externally
    here, so it must not be folded into Tf.

    inj_PMU clamps Tf below 0.05, so the PLL's 0.033 s is not representable and
    the floor is emitted explicitly rather than relying on the clamp.
    """
    wn = float(pmu["Ki"]) ** 0.5
    return [("Tf", max(1.0 / wn, PMU_TF_FLOOR))]


MAX_LOADING = 0.8   # wamces_script.m: max_loading


def effective_rating(mac, sol):
    """Machine rating after the up-rating wamces_script.m applies.

    The script refuses to leave a machine dispatched above 80 % of its
    nameplate and rewrites the rating in place:

        Sg = sqrt(P^2 + Q^2) * Sb        (MVA)
        if Sg > Sr * max_loading: Sr = Sg / max_loading

    Taking `Sr` straight from data_sm.csv therefore disagrees with the model
    actually simulated, for every machine the loop touches. It matters beyond
    bookkeeping: H is per unit on the rating, so the absolute inertia of an
    up-rated machine changes with it, as does the turbine base.

    Returns (rating_MVA, was_uprated).
    """
    i = int(mac["BusID"])
    p = sol[i - 1, 4]
    q = sol[i - 1, 5]
    sr = float(mac["Sr"])
    sg = (p * p + q * q) ** 0.5 * SBASE
    if sg > sr * MAX_LOADING:
        return sg / MAX_LOADING, True
    return sr, False


def write_dyn(path, buses, machines, avrs, psss, turs, gfms, gfls, pmus, sol, fnom=50.0):
    by_id = {int(r["ID"]): r for r in buses}
    out = [
        "! WAMCES dynamic data: 618 synchronous machines with their AVR, PSS and governor.",
        "! Generated by tools/wamces_to_ramses.py. See CLAUDE.md for the model mapping.",
        "! FP = FQ = 0 with explicit P and Q: 613 of the 618 machine buses also carry load,",
        "! so participation fractions would make each machine absorb its bus net injection.",
        "! Pnom = SNOM so the turbine base matches the machine base, as in the MATLAB model.",
        "! Ratings are the up-rated ones: wamces_script.m rewrites Sr for any machine dispatched",
        "! above 80 % of nameplate, which also changes its absolute inertia.",
        "",
        f"FNOM {fnom} ;",
        "",
    ]

    n_uprated = 0
    for k, mac in enumerate(machines):
        i = int(mac["BusID"])
        bus = bus_name(by_id[i])
        p = sol[i - 1, 4] * SBASE
        q = sol[i - 1, 5] * SBASE
        snom, uprated = effective_rating(mac, sol)
        n_uprated += uprated

        exc = " ".join(f"{v:g}" for _, v in exc_st1a_pss2b(avrs[k], psss[k]))
        tor = " ".join(f"{v:g}" for _, v in tor_tgov1(turs[k]))

        out.append(
            f"SYNC_MACH G{i} {bus} 0. 0. {p:.4f} {q:.4f} "
            f"{snom:.1f} {snom:.1f} {float(mac['H']):g} {float(mac['D']):g} 1."
        )
        out.append(
            f"   XT {float(mac['Xl']):g} {float(mac['Xd']):g} {float(mac['Xd1']):g} "
            f"{float(mac['Xd2']):g} {float(mac['Xq']):g} {float(mac['Xq1']):g} "
            f"{float(mac['Xq2']):g} 0. 0. {float(mac['Ra']):g} "
            f"{float(mac['Td01']):g} {float(mac['Td02']):g} "
            f"{float(mac['Tq01']):g} {float(mac['Tq02']):g}"
        )
        out.append(f"   EXC ST1A_PSS2B {exc}")
        out.append(f"   TOR TGOV1 {tor} ;")

    # --- converters and PMUs -------------------------------------------------
    # All three are dispatched at zero in the published power flow, so FP/FQ are
    # zero with explicit zero P and Q: their buses carry load, which stays a
    # residual impedance load exactly as the MATLAB model represents it.
    out.append("")
    for tag, model, rows, params in (
        ("grid-forming converters", "GFOR", gfms, inj_gfor),
        ("grid-following converters", "GFOL", gfls, inj_gfol),
        ("phasor measurement units", "PMU", pmus, inj_pmu),
    ):
        out.append(f"! {len(rows)} {tag}")
        for rec in rows:
            i = int(rec["BusID"])
            vals = " ".join(f"{v:g}" for _, v in params(rec))
            prefix = {"GFOR": "GFM", "GFOL": "GFL", "PMU": "PMU"}[model]
            out.append(
                f"INJEC {model} {prefix}{i} {bus_name(by_id[i])} 0. 0. 0. 0. {vals} ;"
            )
        out.append("")

    path.write_text("\n".join(out))
    return len(machines), n_uprated, len(gfms), len(gfls), len(pmus)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv-dir", default="original-data/csv", type=pathlib.Path,
                    help="directory holding the nine data_*.csv files")
    ap.add_argument("--mat", default="model/powerflow_sol.mat", type=pathlib.Path,
                    help="path to powerflow_sol.mat")
    ap.add_argument("--out-dir", default=".", type=pathlib.Path)
    args = ap.parse_args()

    buses, lines, machines, sol = load_inputs(args.csv_dir, args.mat)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    avrs = read_csv(args.csv_dir / "data_avr.csv")
    psss = read_csv(args.csv_dir / "data_pss.csv")
    turs = read_csv(args.csv_dir / "data_tur.csv")
    for name, tab in (("data_avr", avrs), ("data_pss", psss), ("data_tur", turs)):
        if len(tab) != len(machines):
            sys.exit(f"{name} has {len(tab)} rows, data_sm has {len(machines)}; "
                     "the tables are joined positionally and must match")

    counts, slack_id = write_lf(args.out_dir / "wamces_lf.dat", buses, lines, machines, sol)
    n_lfresv = write_lfres(args.out_dir / "wamces_lfres.dat", buses, sol)
    gfms = read_csv(args.csv_dir / "data_gfm.csv")
    gfls = read_csv(args.csv_dir / "data_gfl.csv")
    pmus = read_csv(args.csv_dir / "data_pmu.csv")
    n_mach, n_uprated, n_gfm, n_gfl, n_pmu = write_dyn(
        args.out_dir / "wamces_dyn.dat", buses, machines, avrs, psss, turs,
        gfms, gfls, pmus, sol)

    print(f"buses      {len(buses)}")
    print(f"lines      {counts['line']}")
    print(f"transfos   {counts['transfo']}")
    print(f"generators {counts['gener']} (slack at bus {slack_id})")
    print(f"LFRESV     {n_lfresv}")
    print(f"SYNC_MACH  {n_mach} (EXC ST1A_PSS2B + TOR TGOV1)")
    print(f"  up-rated {n_uprated} machines dispatched above {MAX_LOADING:.0%} of nameplate")
    print(f"INJEC GFOR {n_gfm}\nINJEC GFOL {n_gfl}\nINJEC PMU  {n_pmu}")


if __name__ == "__main__":
    main()
